---
# Main playbook which applies the different roles and/or tasks to groups and hosts in of the inventory.

#- import_playbook: ./playbooks/commons/playbook.yml
#- import_playbook: ./playbooks/manage_users/playbook.yml

