---
- name: Converge nodes with commons
  hosts: all
  become: true
  gather_facts: true
  force_handlers: true

  vars:
    commontools_update_all: true

  pre_tasks:
    - name: Include common variables and define needed variables.
      # include_vars: "../../../vagrant-ansible-test-vars/vars/common.yml"
      include_vars: "../../../vagrant-ansible-test-vars/vars/admin-accounts.yml"

    - name: Include version-specific variables for CentOS/RHEL.
      include_vars: "../../../vagrant-ansible-test-vars/vars/common/RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
      when: ansible_distribution == 'CentOS' or
            ansible_distribution == 'RedHat' or
            ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Include version-specific variables for Ubuntu.
      include_vars: "../../../vagrant-ansible-test-vars/vars/common/{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
      when: ansible_distribution == 'Ubuntu'

    - name: Include version-specific variables for Debian.
      include_vars: "../../../vagrant-ansible-test-vars/vars/common/{{ ansible_distribution | title }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
      when: ansible_distribution == 'Debian'

    - name: Define commontools_packages_install.
      set_fact:
        commontools_packages_install: "{{ __commontools_packages_install | list }}"
      when: commontools_packages_install is not defined

  roles:
    - { role: repo-epel, when: ansible_os_family == 'RedHat' }
    - { role: common }
